version: '3.8'
services:
  game-server:
    build:
      context: ./game-server
      target: dev
    ports:
      - "8080:8080"
    volumes:
      - ./game-server:/app
    working_dir: /app
    command: go run cmd/flipcup/main.go
    environment:
      - GO_ENV=development

  ui:
    build:
      context: ./ui
      target: dev
    ports:
      - "5173:5173"
    volumes:
      - ./ui:/app
      - /app/node_modules
    working_dir: /app
    command: npm run dev
    environment:
      - VITE_WS_URL=localhost:8080

